########################################
# 프로퍼티 참조 :: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
###  기본 구성
########################################
spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: knc
    ## lcoal
  messages:
    basename: message/message
    encoding: UTF-8
  session:
    store-type: none
  main:
    allow-bean-definition-overriding: true
  application:
    name: knc
    admin:
      enabled: false
  devtools:
    livereload:
      enabled: true
      ## 운영에서는 false
    ##open-in-view=false: true


logging:
  level:
    debug: false
    root: info
    org.springframework.security: debug
    com.zaxxer.hikari: INFO
    co.kr.knc: DEBUG
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: error
    org.springframework.security.web: DEBUG
    co.kr.knc.common.error: trace
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG

#################################################
# security
#################################################
security:
  jwt:
    secretKey: knc
    expireValidInMilliseconds : 3600000

##################################################
# 에러 나는 경우
log:
  error:
    fillInStackTrace: true
    printStackTrace: true
  ruledebug: N

########################################
###  mybatis
########################################

#mybatis:
##  mapper-locations: classpath*:mapper/**/*.xml
####  type-aliases-package: com.dkecofarm.smartfarm.service.**.dto
#  configuration:
#    map-underscore-to-camel-case: on

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

